package main
// Each new term in the Fibonacci sequence is generated by adding 
// the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed 
// four million, find the sum of the even-valued terms.
import (
	"fmt"
)

func isEven(number int) bool {
	if number < 2 {
		return false
	} else {
		return number % 2 == 0
	}		
}

func main() {
	bound := 4000000
	sum := 0
	for prev, cur, n:=0, 1, 1; cur<bound; n++ {
		prev, cur = cur, cur+prev
		if isEven(cur) {
			sum += cur
		}
                fmt.Printf("Termino %d: %d. Sum of Even: %d\n", n, cur, sum)
	}
	fmt.Printf("The Sum of even-valued of Fibonacci serie is: %d\n", sum)
}
